[package]
name = "the-swarm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
futures = "0.3"
libp2p = "0.45.1"
tokio = { version = "1.19.2", features = ["full"] }
void = "1.0.2"
serde = "1.0.138"
