[package]
name = "the-swarm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
clap = { version = "3.2.8", features = ["derive"] }
futures = "0.3"
libp2p = { version = "0.45.1", features = ["serde", "tcp-tokio"] }
# Add integration of actual consensus
# rust-hashgraph = { git = "..." }
rand = "0.8.4"
tokio = { version = "1.19.2", features = ["full"] }
tracing = "0.1.35"
tracing-subscriber = "0.3.14"
void = "1.0.2"
serde = "1.0.138"
serde_json = "1.0.82"
