version: "3.9"

x-node: &node
  build:
    context: ./
    dockerfile: ./the-swarm/Dockerfile
  volumes:
    - ./logs/docker:/app/logs
  # 2 data + 2 parity = 4 shards = 4 nodes
  command: ["--parity-shards", "2"]
  network_mode: "host"

services:
  node-1:
    <<: *node
  node-2:
    <<: *node
  node-3:
    <<: *node

